fields_route = {
    'skitouring': {
        'fields': [
            'locales.title',
            'locales.summary',
            'locales.description',
            'locales.slope',
            'locales.remarks',
            'locales.gear',
            'locales.external_resources',
            'locales.route_history',
            'geometry.geom',
            'geometry.geom_detail',
            'activities',
            'elevation_min',
            'elevation_max',
            'height_diff_up',
            'height_diff_down',
            'route_length',
            'height_diff_access',
            'height_diff_difficulties',
            'route_types',
            'orientations',
            'durations',
            'glacier_gear',
            'configuration',
            'lift_access',
            'ski_rating',
            'ski_exposition',
            'labande_ski_rating',
            'labande_global_rating'
        ],
        'required': [
            'locales',
            'locales.title',
            'activities'
        ],
        'listing': [
            'locales.title',
            'locales.summary',
            'elevation_max'
        ]
    },
    'snow_ice_mixed': {
        'fields': [
            'locales.title',
            'locales.summary',
            'locales.description',
            'locales.slope',
            'locales.remarks',
            'locales.gear',
            'locales.external_resources',
            'locales.route_history',
            'geometry.geom',
            'geometry.geom_detail',
            'activities',
            'elevation_min',
            'elevation_max',
            'height_diff_up',
            'height_diff_down',
            'route_length',
            'difficulties_height',
            'height_diff_access',
            'height_diff_difficulties',
            'route_types',
            'orientations',
            'durations',
            'glacier_gear',
            'configuration',
            'lift_access',
            'global_rating',
            'engagement_rating',
            'risk_rating',
            'equipment_rating',
            'ice_rating',
            'mixed_rating',
            'rock_types'
        ],
        'required': [
            'locales',
            'locales.title',
            'activities'
        ],
        'listing': [
            'locales.title',
            'locales.summary',
            'elevation_max'
        ]
    },
    'mountain_climbing': {
        'fields': [
            'locales.title',
            'locales.summary',
            'locales.description',
            'locales.remarks',
            'locales.gear',
            'locales.external_resources',
            'locales.route_history',
            'geometry.geom',
            'geometry.geom_detail',
            'activities',
            'elevation_min',
            'elevation_max',
            'height_diff_up',
            'height_diff_down',
            'route_length',
            'difficulties_height',
            'height_diff_access',
            'height_diff_difficulties',
            'route_types',
            'orientations',
            'durations',
            'glacier_gear',
            'configuration',
            'lift_access',
            'global_rating',
            'engagement_rating',
            'risk_rating',
            'equipment_rating',
            'exposition_rock_rating',
            'rock_free_rating',
            'rock_required_rating',
            'aid_rating',
            'rock_types'
        ],
        'required': [
            'locales',
            'locales.title',
            'activities'
        ],
        'listing': [
            'locales.title',
            'locales.summary',
            'elevation_max'
        ]
    },
    'rock_climbing': {
        'fields': [
            'locales.title',
            'locales.summary',
            'locales.description',
            'locales.remarks',
            'locales.gear',
            'locales.external_resources',
            'locales.route_history',
            'geometry.geom',
            'geometry.geom_detail',
            'activities',
            'elevation_min',
            'elevation_max',
            'height_diff_up',
            'height_diff_down',
            'difficulties_height',
            'height_diff_access',
            'height_diff_difficulties',
            'route_types',
            'orientations',
            'durations',
            'glacier_gear',
            'configuration',
            'lift_access',
            'global_rating',
            'engagement_rating',
            'risk_rating',
            'equipment_rating',
            'exposition_rock_rating',
            'rock_free_rating',
            'rock_required_rating',
            'aid_rating',
            'rock_types',
            'climbing_outdoor_types'
        ],
        'required': [
            'locales',
            'locales.title',
            'activities'
        ],
        'listing': [
            'locales.title',
            'locales.summary',
            'elevation_max'
        ]
    },
    'ice_climbing': {
        'fields': [
            'locales.title',
            'locales.summary',
            'locales.description',
            'locales.slope',
            'locales.remarks',
            'locales.gear',
            'locales.external_resources',
            'locales.route_history',
            'geometry.geom',
            'geometry.geom_detail',
            'activities',
            'elevation_min',
            'elevation_max',
            'height_diff_up',
            'height_diff_down',
            'difficulties_height',
            'height_diff_access',
            'height_diff_difficulties',
            'route_types',
            'orientations',
            'durations',
            'glacier_gear',
            'lift_access',
            'global_rating',
            'engagement_rating',
            'risk_rating',
            'equipment_rating',
            'ice_rating',
            'mixed_rating'
        ],
        'required': [
            'locales',
            'locales.title',
            'activities'
        ],
        'listing': [
            'locales.title',
            'locales.summary',
            'elevation_max'
        ]
    },
    'hiking': {
        'fields': [
            'locales.title',
            'locales.summary',
            'locales.description',
            'locales.remarks',
            'locales.gear',
            'locales.external_resources',
            'locales.route_history',
            'geometry.geom',
            'geometry.geom_detail',
            'activities',
            'elevation_min',
            'elevation_max',
            'height_diff_up',
            'height_diff_down',
            'route_length',
            'difficulties_height',
            'height_diff_access',
            'height_diff_difficulties',
            'route_types',
            'orientations',
            'durations',
            'lift_access',
            'hiking_rating',
            'hiking_mtb_exposition'

        ],
        'required': [
            'locales',
            'locales.title',
            'activities'
        ],
        'listing': [
            'locales.title',
            'locales.summary',
            'elevation_max'
        ]
    },
    'snowshoeing': {
        'fields': [
            'locales.title',
            'locales.summary',
            'locales.description',
            'locales.slope',
            'locales.remarks',
            'locales.gear',
            'locales.external_resources',
            'locales.route_history',
            'geometry.geom',
            'geometry.geom_detail',
            'activities',
            'elevation_min',
            'elevation_max',
            'height_diff_up',
            'height_diff_down',
            'route_length',
            'difficulties_height',
            'height_diff_access',
            'height_diff_difficulties',
            'route_types',
            'orientations',
            'durations',
            'glacier_gear',
            'configuration',
            'lift_access',
            'snowshoe_rating'

        ],
        'required': [
            'locales',
            'locales.title',
            'activities'
        ],
        'listing': [
            'locales.title',
            'locales.summary',
            'elevation_max'
        ]
    },
    'moutain_biking': {
        'fields': [
            'locales.title',
            'locales.summary',
            'locales.description',
            'locales.remarks',
            'locales.gear',
            'locales.external_resources',
            'locales.route_history',
            'geometry.geom',
            'geometry.geom_detail',
            'activities',
            'elevation_min',
            'elevation_max',
            'height_diff_up',
            'height_diff_down',
            'route_length',
            'difficulties_height',
            'height_diff_access',
            'height_diff_difficulties',
            'route_types',
            'orientations',
            'durations',
            'lift_access',
            'hiking_mtb_exposition',
            'mtb_up_rating',
            'mtb_down_rating',
            'mtb_length_asphalt',
            'mtb_length_trail',
            'mtb_height_diff_portages'
        ],
        'required': [
            'locales',
            'locales.title',
            'activities'
        ],
        'listing': [
            'locales.title',
            'locales.summary',
            'elevation_max'
        ]
    },
    'via_ferrata': {
        'fields': [
            'locales.title',
            'locales.summary',
            'locales.description',
            'locales.remarks',
            'locales.gear',
            'locales.external_resources',
            'locales.route_history',
            'geometry.geom',
            'geometry.geom_detail',
            'activities',
            'elevation_min',
            'elevation_max',
            'height_diff_up',
            'height_diff_down',
            'route_length',
            'difficulties_height',
            'height_diff_access',
            'height_diff_difficulties',
            'route_types',
            'orientations',
            'durations',
            'configuration',
            'lift_access',
            'engagement_rating',
            'equipment_rating',
            'via_ferrata_rating',
            'rock_types'
        ],
        'required': [
            'locales',
            'locales.title',
            'activities'
        ],
        'listing': [
            'locales.title',
            'locales.summary',
            'elevation_max'
        ]
    }
}
